-- WHITELINEZ Supabase schema (aligned with current backend/frontend code)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Tables
CREATE TABLE IF NOT EXISTS cameras (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name         TEXT NOT NULL,
  ipcam_alias  TEXT UNIQUE,
  stream_url   TEXT NOT NULL DEFAULT '',
  count_line   JSONB,
  detect_zone  JSONB,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bet_rounds (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  camera_id    UUID REFERENCES cameras ON DELETE SET NULL,
  market_type  TEXT NOT NULL, -- over_under | vehicle_count | vehicle_type | custom
  params       JSONB NOT NULL DEFAULT '{}',
  status       TEXT DEFAULT 'upcoming', -- upcoming|open|locked|resolved|cancelled
  opens_at     TIMESTAMPTZ,
  closes_at    TIMESTAMPTZ,
  ends_at      TIMESTAMPTZ,
  result       JSONB,
  created_at   TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS markets (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  round_id     UUID REFERENCES bet_rounds ON DELETE CASCADE,
  label        TEXT NOT NULL,
  outcome_key  TEXT NOT NULL,
  odds         NUMERIC(5,2) NOT NULL,
  total_staked INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bets (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id             UUID REFERENCES auth.users NOT NULL,
  round_id            UUID REFERENCES bet_rounds NOT NULL,
  market_id           UUID REFERENCES markets,
  amount              INT NOT NULL CHECK (amount > 0),
  potential_payout    INT NOT NULL,
  status              TEXT DEFAULT 'pending', -- pending|won|lost|cancelled
  bet_type            TEXT NOT NULL DEFAULT 'market', -- market|exact_count
  window_start        TIMESTAMPTZ,
  window_duration_sec INT,
  vehicle_class       TEXT,
  exact_count         INT,
  baseline_count      INT DEFAULT 0,
  actual_count        INT,
  placed_at           TIMESTAMPTZ DEFAULT now(),
  resolved_at         TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS count_snapshots (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  camera_id         UUID REFERENCES cameras ON DELETE SET NULL,
  captured_at       TIMESTAMPTZ DEFAULT now(),
  count_in          INT DEFAULT 0,
  count_out         INT DEFAULT 0,
  total             INT DEFAULT 0,
  vehicle_breakdown JSONB
);

CREATE TABLE IF NOT EXISTS user_balances (
  user_id UUID REFERENCES auth.users PRIMARY KEY,
  balance INT NOT NULL DEFAULT 1000 CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID REFERENCES auth.users,
  username   TEXT NOT NULL,
  content    TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 280),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ml_detection_events (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  camera_id            UUID REFERENCES cameras ON DELETE SET NULL,
  captured_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  model_name           TEXT NOT NULL,
  model_conf_threshold NUMERIC(5,4) NOT NULL,
  detections_count     INT NOT NULL DEFAULT 0,
  avg_confidence       NUMERIC(5,4) NOT NULL DEFAULT 0,
  class_counts         JSONB NOT NULL DEFAULT '{}'::jsonb,
  new_crossings        INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ml_training_jobs (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_type          TEXT NOT NULL, -- export|train|evaluate|deploy
  status            TEXT NOT NULL, -- queued|running|completed|failed|cancelled
  provider          TEXT NOT NULL DEFAULT 'internal_stub',
  started_at        TIMESTAMPTZ,
  completed_at      TIMESTAMPTZ,
  params            JSONB NOT NULL DEFAULT '{}'::jsonb,
  metrics           JSONB NOT NULL DEFAULT '{}'::jsonb,
  artifact_manifest JSONB,
  notes             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ml_model_registry (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_name      TEXT NOT NULL,
  model_uri       TEXT NOT NULL,
  base_model      TEXT,
  training_job_id BIGINT REFERENCES ml_training_jobs(id) ON DELETE SET NULL,
  status          TEXT NOT NULL DEFAULT 'candidate', -- candidate|active|archived|failed
  metrics         JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  promoted_at     TIMESTAMPTZ
);

-- Backfill/upgrade columns for older installs
ALTER TABLE cameras ADD COLUMN IF NOT EXISTS detect_zone JSONB;

ALTER TABLE bets ADD COLUMN IF NOT EXISTS bet_type TEXT NOT NULL DEFAULT 'market';
ALTER TABLE bets ADD COLUMN IF NOT EXISTS window_start TIMESTAMPTZ;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS window_duration_sec INT;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS vehicle_class TEXT;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS exact_count INT;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS baseline_count INT DEFAULT 0;
ALTER TABLE bets ADD COLUMN IF NOT EXISTS actual_count INT;
ALTER TABLE bets ALTER COLUMN market_id DROP NOT NULL;

-- Convert legacy unique(user_id, market_id) constraint to partial unique index
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_name = 'bets'
      AND constraint_type = 'UNIQUE'
      AND constraint_name = 'bets_user_id_market_id_key'
  ) THEN
    ALTER TABLE bets DROP CONSTRAINT bets_user_id_market_id_key;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS uniq_market_bet_per_user_market
  ON bets(user_id, market_id)
  WHERE bet_type = 'market' AND market_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bets_round_status_type ON bets(round_id, status, bet_type);
CREATE INDEX IF NOT EXISTS idx_snapshots_camera_time ON count_snapshots(camera_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ml_events_camera_time ON ml_detection_events(camera_id, captured_at DESC);
CREATE INDEX IF NOT EXISTS idx_ml_jobs_created_at ON ml_training_jobs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ml_models_status_promoted ON ml_model_registry(status, promoted_at DESC);

-- Seed camera
INSERT INTO cameras (name, ipcam_alias, stream_url, is_active)
SELECT 'Kingston Feed', NULL, '', TRUE
WHERE NOT EXISTS (SELECT 1 FROM cameras WHERE name = 'Kingston Feed');

-- RLS
ALTER TABLE cameras ENABLE ROW LEVEL SECURITY;
ALTER TABLE bet_rounds ENABLE ROW LEVEL SECURITY;
ALTER TABLE markets ENABLE ROW LEVEL SECURITY;
ALTER TABLE bets ENABLE ROW LEVEL SECURITY;
ALTER TABLE count_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE ml_detection_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE ml_training_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ml_model_registry ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS public_read_cameras ON cameras;
DROP POLICY IF EXISTS admin_write_cameras ON cameras;
CREATE POLICY public_read_cameras ON cameras
  FOR SELECT USING (true);
CREATE POLICY admin_write_cameras ON cameras
  FOR ALL USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS public_read_rounds ON bet_rounds;
CREATE POLICY public_read_rounds ON bet_rounds
  FOR SELECT USING (true);

DROP POLICY IF EXISTS public_read_markets ON markets;
CREATE POLICY public_read_markets ON markets
  FOR SELECT USING (true);

DROP POLICY IF EXISTS own_bets_select ON bets;
DROP POLICY IF EXISTS own_bets_insert ON bets;
DROP POLICY IF EXISTS public_bets_activity_read ON bets;
CREATE POLICY own_bets_select ON bets
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY own_bets_insert ON bets
  FOR INSERT WITH CHECK (auth.uid() = user_id);
-- Required for public activity feed on landing page
CREATE POLICY public_bets_activity_read ON bets
  FOR SELECT USING (true);

DROP POLICY IF EXISTS public_read_snapshots ON count_snapshots;
CREATE POLICY public_read_snapshots ON count_snapshots
  FOR SELECT USING (true);

DROP POLICY IF EXISTS own_balance_select ON user_balances;
CREATE POLICY own_balance_select ON user_balances
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS public_read_messages ON messages;
DROP POLICY IF EXISTS auth_insert_messages ON messages;
CREATE POLICY public_read_messages ON messages
  FOR SELECT USING (true);
CREATE POLICY auth_insert_messages ON messages
  FOR INSERT
  WITH CHECK (auth.role() = 'authenticated' AND auth.uid() = user_id);

DROP POLICY IF EXISTS admin_read_ml_events ON ml_detection_events;
CREATE POLICY admin_read_ml_events ON ml_detection_events
  FOR SELECT USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS admin_rw_ml_jobs ON ml_training_jobs;
CREATE POLICY admin_rw_ml_jobs ON ml_training_jobs
  FOR ALL USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

DROP POLICY IF EXISTS admin_rw_ml_models ON ml_model_registry;
CREATE POLICY admin_rw_ml_models ON ml_model_registry
  FOR ALL USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- Functions
CREATE OR REPLACE FUNCTION place_bet_atomic(
  p_user_id UUID,
  p_round_id UUID,
  p_market_id UUID,
  p_amount INT,
  p_potential_payout INT
) RETURNS JSON
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_balance INT;
  v_bet_id UUID;
BEGIN
  INSERT INTO user_balances (user_id, balance)
  VALUES (p_user_id, 1000)
  ON CONFLICT (user_id) DO NOTHING;

  SELECT balance INTO v_balance
  FROM user_balances
  WHERE user_id = p_user_id
  FOR UPDATE;

  IF v_balance < p_amount THEN
    RETURN json_build_object('error', 'Insufficient balance');
  END IF;

  UPDATE user_balances
  SET balance = balance - p_amount
  WHERE user_id = p_user_id;

  INSERT INTO bets (
    user_id, round_id, market_id, amount, potential_payout, status, bet_type
  )
  VALUES (
    p_user_id, p_round_id, p_market_id, p_amount, p_potential_payout, 'pending', 'market'
  )
  RETURNING id INTO v_bet_id;

  UPDATE markets
  SET total_staked = total_staked + p_amount
  WHERE id = p_market_id;

  RETURN json_build_object('bet_id', v_bet_id);
END;
$$;

CREATE OR REPLACE FUNCTION get_user_balance(p_user_id UUID)
RETURNS INT
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO user_balances (user_id, balance)
  VALUES (p_user_id, 1000)
  ON CONFLICT (user_id) DO NOTHING;

  RETURN (SELECT balance FROM user_balances WHERE user_id = p_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION set_user_balance(p_user_id UUID, p_balance INT)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO user_balances (user_id, balance)
  VALUES (p_user_id, GREATEST(0, p_balance))
  ON CONFLICT (user_id)
  DO UPDATE SET balance = GREATEST(0, EXCLUDED.balance);
END;
$$;

CREATE OR REPLACE FUNCTION credit_user_balance(p_user_id UUID, p_amount INT)
RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO user_balances (user_id, balance)
  VALUES (p_user_id, p_amount)
  ON CONFLICT (user_id) DO UPDATE
    SET balance = user_balances.balance + EXCLUDED.balance;
END;
$$;

-- Realtime tables used by frontend subscriptions
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE bets;
  EXCEPTION WHEN duplicate_object THEN NULL;
  END;
END $$;
